### ISSUE TITLE
Documentation on how to use `sensor.leaf1niss_battery_capacity` to report charging in the energy dashboard 

### ISSUE THREAD

**Issue by calamarain** [remuslazar/homeassistant-carwings#10]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Thanks a lot for writing and maintaining this integration!
It would be great to use the newly available `sensor.leaf1niss_battery_capacity` to measure how much energy has been used to charge the car.

### Describe the solution you'd like

I'm unsure how to do this, but I'm sure people with actual programming experience can think of a good solution. I suppose the documentation of this integration would be a good place to document an example.
- It should increase when the car is charged, and not reset. A utility meter seems a good fit.
- It should only measure increase in charge, not a decrease.
- It should be togglable for when the car is charged at the energy meter connected to the HASS instance or not. 

### Describe alternatives you've considered

- Ask on the HASS Discord, but the people there wouldn't have any context or benefit for a solution.
- Ask to add a utility meter to the integration, but I'm not sure that should be part of the integration itself.
- Try to create something myself.

### Additional context

No additional context.

**Comment by calamarain** [comment]
My [charging station](https://github.com/SmartEVSE/SmartEVSE-3) doesn't have an energy meter. Using the car's value seems like a good enough estimate for my use case, of getting insight into my home's energy use.
Perhaps the best solution then is to create an automation that toggles (and resets?) a standard HASS utility meter?

**Comment by Arquiteto** [comment]
I think you can perfectly achieve what you described using an utility
meter.

pon., 22 lip 2024, 10:04 użytkownik Remus Lazar ***@***.***>
napisał:

**Comment by calamarain** [comment]
That would be great. What would be required? Because the value of the utility meter should only change when the car is charging, and it should start counting up from whatever value the car has when it starts charging.

Looking at the form for creating a utility meter in HASS, it seems like the 'Periodically resetting' functionality should be used, it doesn't reset to 0, though.
<img width="473" alt="image" src="https://github.com/user-attachments/assets/7b970b06-f50b-4a73-a711-4daabd94140e">
Any ideas on how this could be made to work?

**Comment by Arquiteto** [comment]
AFAIK as long as you don't set your utility meter to netto it will only
count when the source sensor is increasing.

pon., 22 lip 2024, 11:33 użytkownik calamarain ***@***.***>
napisał:

**Comment by calamarain** [comment]
Ok. So what would a utility meter do if the input resets to a value > 0?

**Comment by Arquiteto** [comment]
Remain constant

pon., 22 lip 2024, 13:09 użytkownik calamarain ***@***.***>
napisał:

**Comment by calamarain** [comment]
A solution is to create a utility meter with these settings:
- Net consumption: disabled
- Delta values: disabled
- Periodically resetting: enabled
- Sensor always available: enabled

<img width="522" alt="image" src="https://github.com/user-attachments/assets/f49aa3e0-cf29-4c08-a9f0-0a76faf05c62">


If you like the utility meter to only measure conditionally, create two tariffs, e.g., 'on' and 'off'. I used this to only measure when my charge point at home is charging.
