### ISSUE TITLE
pycarwings3~=0.7.1 not found on HASS 2024.8.0

### ISSUE THREAD

**Issue by calamarain** [remuslazar/homeassistant-carwings#17]
## System Information

version | core-2024.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1387
Downloaded Repositories | 8

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 439.4 GB
disk_used | 266.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), File editor (5.8.0), ESPHome (2024.7.3), NGINX Home Assistant SSL proxy (3.9.0), Let's Encrypt (5.0.26), Home Assistant Google Drive Backup (0.112.1), SQLite Web (4.2.0), InfluxDB (5.0.0), Samba share (12.3.2), Terminal & SSH (9.14.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 1
views | 5
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | April 11, 2024 at 20:39
-- | --
current_recorder_run | August 8, 2024 at 03:43
estimated_db_size | 9907.01 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After updating to HASS 2024.8.0
Using version e33c46b

```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 03:43:58 (1 occurrences)
Last logged: 03:43:58

Setup failed for custom integration 'nissan_carwings': Requirements for nissan_carwings not found: ['pycarwings3~=0.7.1'].
```

### Reproduction steps

1. Update to HASS 2024.8.0
2. View error in notification

### Debug logs

```text
On request.
```

### Diagnostics dump

Is not there.

**Comment by remuslazar** [comment]
There is an issue in pycarwings 0.7.1 with the aiohttp version being incompatible with the version used by the current HASS. I am about to solve this issue in pycarwings3 and I am looking forward to provide a fix soon..

**Comment by remuslazar** [comment]
@calamarain a simple HASS restart should fix it! I was able to fix the issue in carwings3, a restart should pick the current patch level release (0.7.2) from PyPI.

**Comment by calamarain** [comment]
I don't know how you did it, but it is fixed now after a restart.
I've restarted earlier today, it didn't solve the problem then.

Thanks for the response!
