### ISSUE TITLE
AC temperature set

### ISSUE THREAD

**Issue by alesaund** [remuslazar/homeassistant-carwings#32]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Would be useful tu set temperature for AC

### Describe the solution you'd like

Set a input number box for the temperature

### Describe alternatives you've considered

.

### Additional context

.

**Comment by remuslazar** [comment]
This will be a cool feature, though. Unfortunately not available via API..
