### ISSUE TITLE
Temp setting for the climate control

### ISSUE THREAD

**Issue by CinaedPhoenix** [remuslazar/homeassistant-carwings#43]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

In the nissan app, one can choose the "target" cabine temperature, before sending the request.
Is it possible to add this feature to the integration?

### Describe the solution you'd like

Add an sensor which can be set to an Interger between 16-30.
Then include this value in the command to turn on the climate control

### Describe alternatives you've considered

To be honest, I don't see any other way to implement it...

### Additional context

....honestly, why put in a required field with "additional context"... 😉

**Comment by remuslazar** [comment]
@CinaedPhoenix IMO this feature is not available via the carwings API, I have also checked the current version of the nissan App (for iOS: https://apps.apple.com/de/app/nissanconnect-ev/id407497029). Am I missing something here? Could you please elaborate more on that and send some screenshots?

Thanks!

**Comment by CinaedPhoenix** [comment]
@remuslazar 

Hi, thanks for the response!

You might be right, I don't see much about it when looking in the carwings github... can't shake the feeling that it must be availiable though...
Otherwise, why would they include it in the app...?
![image](https://github.com/user-attachments/assets/fcb4d2a0-264c-47c4-ae5b-3d0bd160b4c8)

**Comment by CinaedPhoenix** [comment]
Hi again

the "type" ClimateStatus should be able to pull the "preset temperature", though i don't see a reference to set it... ☹

From: https://pkg.go.dev/github.com/joeshaw/carwings#ClimateStatus

type ClimateStatus struct {
	// Date and time this status was retrieved from the vehicle.
	LastOperationTime time.Time

	// The current climate control operation status.
	Running bool

	// Current plugged-in state
	PluginState PluginState

	// The amount of time the climate control system will run
	// while on battery power, in seconds.
	BatteryDuration int

	// The amount of time the climate control system will run
	// while plugged in, in seconds.
	PluggedDuration int

	// The climate preset temperature unit, F or C
	TemperatureUnit string

	// The climate preset temperature value
	Temperature int

	// Time the AC was stopped, or is scheduled to stop
	ACStopTime time.Time

	// Estimated cruising range with climate control on, in
	// meters.
	CruisingRangeACOn int

	// Estimated cruising range with climate control off, in
	// meters.
	CruisingRangeACOff int
}

**Comment by remuslazar** [comment]
Yes, pulling the current temperature could be easily implemented. I don’t see much value in it, though.

It seems that setting the temperature via app has no effect, at least for vehicles <2019. see https://groups.google.com/g/my-leaf/c/SiAK5GypPOQ

**Comment by CinaedPhoenix** [comment]
...Must admit, I kind'a suspected as much... whenever I set a temperature, it does not seem to go "all the way up or down" to the correct temp, I just figured it would run the AC in a "low power mode though... or something...

Yeah, it would be nice to have, but no, it's not truly important...

Thanks for having a look around.

...Great addin by the way, seems way less "fiddly" than the official implementation.
