### ISSUE TITLE
Logo missing

### ISSUE THREAD

**Issue by tonysprenk** [remuslazar/homeassistant-carwings#47]
## System Information

version | core-2024.9.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.31-haos-raspi
arch | aarch64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4910
Installed Version | 2.0.1
Stage | running
Available Repositories | 1396
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 January 2018 at 01:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | null
certificate_status | null
instance_id | 565ccb03edae472f88d6b4335c4c9263
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 116.5 GB
disk_used | 26.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Home Assistant Google Drive Backup (0.112.1), File editor (5.8.0), Cloudflared (5.1.19), 3DPrinter (2023.1.0), Advanced SSH & Web Terminal (18.0.0), Samba share (12.3.2), ESPHome (2024.8.3), iSponsorBlockTV add-on (2.1.0), Matter Server (6.4.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 4
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 17 August 2024 at 05:29
-- | --
current_recorder_run | 10 September 2024 at 06:20
estimated_db_size | 805.71 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

The logo is missing. 
![IMG_1711](https://github.com/user-attachments/assets/7067bd65-c32e-4654-a334-2bbf9a3eda22)

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
Nvt
```

**Comment by remuslazar** [comment]
Relates https://github.com/home-assistant/brands/pull/5739

**Comment by remuslazar** [comment]
The related PR has been merged
