### ISSUE TITLE
INVALID PARAMS error during Integration setup

### ISSUE THREAD

**Issue by kernel610** [remuslazar/homeassistant-carwings#6]
## System Information

version | core-2024.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | America/Chicago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1414
Downloaded Repositories | 102

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 47

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | September 18, 2024 at 7:00 PM
relayer_connected | true
relayer_region | us-east-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | true
remote_server | us-east-1-0.ui.nabu.casa
certificate_status | ready
instance_id | *********REDACTED*********
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 60.3 GB
disk_used | 22.0 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Z-Wave JS UI (3.8.5), File editor (5.8.0), Mosquitto broker (6.4.1), Node-RED (18.0.4), Home Assistant Google Drive Backup (0.112.1), ESPHome (2024.6.6), Vaultwarden (Bitwarden) (0.22.0), Z-Wave JS (0.6.2), rtl_433 (0.5.2), Grocy (0.21.0), Matter Server (6.2.1), Zigbee2MQTT (1.39.0-1), Terminal & SSH (9.14.0), Studio Code Server (5.15.0), rtlamr2mqtt (2.3.4)

</details>

<details><summary>keymaster</summary>

zwave_integration | zwave_js
-- | --
network_status | on

</details>

<details><summary>Dashboards</summary>

dashboards | 9
-- | --
resources | 65
views | 60
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | July 8, 2024 at 5:22 PM
-- | --
current_recorder_run | July 15, 2024 at 1:44 PM
estimated_db_size | 1577.49 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I'm receiving an authentication error when setting up the integration. In the logs it appears the issue is due to an INVALID PARAMS: -2010 error.

### Reproduction steps

1. Install integration using the instructed method in the readme file
2. Navigate to Integrations
3. Click Add integration to choose the Nissan Connect (Carwings) integration
![image](https://github.com/user-attachments/assets/d12ccba8-1255-4f54-9891-48baf366cf8b)
4. Enter email address and password for Nissan Connect.
5. Choose NNA (USA) option under Region
6. Do not touch the API endpoint field
7. Click Submit.
8. Integration tries to install but returns Authentication failed error.
![image](https://github.com/user-attachments/assets/ee231558-d52f-4c41-9f64-6cbc88c89f41)
9. System log return several error entries. Below are the entries in time sequence. The only special character the password contains is an exclamation mark.
```
This error originated from a custom integration.

Logger: pycarwings3.pycarwings3
Source: custom_components/nissan_carwings/api.py:100
integration: nissan_carwings (documentation, issues)
First occurred: 2:34:16 PM (1 occurrences)
Last logged: 2:34:16 PM

carwings error INVALID PARAMS: -2010
```
```
This error originated from a custom integration.

Logger: custom_components.nissan_carwings
Source: custom_components/nissan_carwings/api.py:110
integration: nissan_carwings (documentation, issues)
First occurred: 2:34:16 PM (1 occurrences)
Last logged: 2:34:16 PM

Login failed: username=**EMAIL REDACTED**@yahoo.com, region=NNA
```
```
This error originated from a custom integration.

Logger: custom_components.nissan_carwings
Source: custom_components/nissan_carwings/config_flow.py:43
integration: nissan_carwings (documentation, issues)
First occurred: 2:34:16 PM (1 occurrences)
Last logged: 2:34:16 PM

Authentication error: "Error fetching information - INVALID PARAMS"
```

**Comment by remuslazar** [comment]
@kernel610 thank you for testing! The error "INVALID PARAMS" is being thrown when the nissan API was not able to authenticate the user credentials.

Please note that this integration only works with older nissan vehicles (24 , 40kWh Models) like the core `nissan_leaf` integration. For newer vehicles this integration should be the right one:

https://github.com/dan-r/HomeAssistant-NissanConnect

**Comment by kernel610** [comment]
> @kernel610 does this issue still exist with the current release?

The car I was testing is a 2020 U.S. model which I understood doesn't have any supported integrations due to Nissan North America's API restrictions. I can test again though if it should work now.

**Comment by remuslazar** [comment]
@kernel610 thank you for the clarification. Unfortunately this integration is not the right one but you could try this one https://github.com/dan-r/HomeAssistant-NissanConnect

**Comment by randyoo** [comment]
> @kernel610 thank you for testing! The error "INVALID PARAMS" is being thrown when the nissan API was not able to authenticate the user credentials.
> 
> Please note that this integration only works with older nissan vehicles (24 , 40kWh Models) like the core `nissan_leaf` integration. For newer vehicles this integration should be the right one:
> 
> https://github.com/dan-r/HomeAssistant-NissanConnect

Just a suggestion: maybe this info could go at the top of the readme?
