### ISSUE TITLE
Climate control switch unavailable after toggle

### ISSUE THREAD

**Issue by jchristianj** [remuslazar/homeassistant-carwings#7]
## System Information

version | core-2024.7.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.33-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4994
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | July 18, 2024, 02:00
relayer_connected | true
relayer_region | eu-central-1
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
remote_server | eu-central-1-17.ui.nabu.casa
certificate_status | ready
instance_id | c9b47baf5c974fb88ec11254a4cb201a
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 12.4
-- | --
update_channel | stable
supervisor_version | supervisor-2024.06.2
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 46.5 GB
disk_used | 14.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.8.0), Node-RED (18.0.4), Advanced SSH & Web Terminal (18.0.0), Filebrowser (2.23.0_14), Mosquitto broker (6.4.1), Ring-MQTT with Video Streaming (5.6.7), Studio Code Server (5.15.0), Govee to MQTT Bridge (2024.07.13-82ddc6e9), Matter Server (6.3.0), SQLite Web (4.1.2), ESPHome (2024.6.6), Firefox (1.2.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 0
views | 25
mode | storage

</details>

<details><summary>Miele</summary>

component_version | 2024.5.0
-- | --
reach_miele_cloud | ok

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | June 26, 2024, 10:38
-- | --
current_recorder_run | July 16, 2024, 22:32
estimated_db_size | 883.95 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi! First of all - thanks for making this HACS integration, very useful for me and us Nissan Leaf owners!
In my setup, there is an issue with the climate control switch: As soon as I toggle it, the switch becomes unavailable. To bring it back, the integration needs to be restarted.

### Reproduction steps

1. toggle climate control switch
2. switch becomes unavailable

[home-assistant_nissan_carwings_2024-07-17T07-56-59.518Z.log](https://github.com/user-attachments/files/16262324/home-assistant_nissan_carwings_2024-07-17T07-56-59.518Z.log)

### Debug logs

```text
attached as file
```

### Diagnostics dump

not available

**Comment by remuslazar** [comment]
@jchristianj thanks for testing and for this detailed report!

It works as intended: because switching on the AC is an async process and cannot be cancelled, the switch will stick in the disabled state until the operation finishes (and the car has reported that the AC is actually ON). If there are errors of any kind, the switch will return to an enabled state and will reflect the current state of the AC.

The whole AC logic is not fully tested, though.

Do you find the disabled state weird? There is no other state like "progressing" in HASS; this would be ideal.

**Comment by jchristianj** [comment]
Hi, no the status itself is not weird, but there are log entries and notifications indicating failures when that switch is operated, which is a bit misleading. Anyhow, I could live with that.
But in my case the switch does never come back to normal status: Once toggled to on, it remains unavailable forever. I need to reload the integration to bring it back. After toggling, the car reports "climate on" within a minute via the Nissan App on my iPhone, I can see climate is running (car is in the driveway), but the HA climate switch remains unavailable. It does not go to ON position to indicate the climate is running.
By the way, the same applies to the "request update" button. It never comes back to normal as well, need a integration restart to make it work again.

**Comment by remuslazar** [comment]
thanks. I will take a look into that.. at least in my case the request update button works well. Please note that an update may take some time, the timeout being set to 10 minutes. After 10 minutes the button should be enabled. Could you please verify that? Just wait 10 minutes to see if it works?

**Comment by jchristianj** [comment]
I've been too impatient. Can confirm that the request update button comes back within 10 minutes. But I have the impression that it does not do anything? The timestamp in the attributes, e.g. for battery charge level, remains an older one and does not refresh to the time I pressed the update button, even if I wait a few minutes after update request.

**Comment by remuslazar** [comment]
> I've been too impatient. Can confirm that the request update button comes back within 10 minutes. But I have the impression that it does not do anything? The timestamp in the attributes, e.g. for battery charge level, remains an older one and does not refresh to the time I pressed the update button, even if I wait a few minutes after update request.

the timestamp of the attribute will change only if the SOC will also change. To see the update timestamp, see the additional attributes of the entity. There is a timestamp property available which reflects the time the status was last updated.
