### ISSUE TITLE
Start charging button

### ISSUE THREAD

**Issue by jchristianj** [remuslazar/homeassistant-carwings#8]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hi, the old core integration included a button to start charging (if the car was plugged in). Does your integration provide this button as well? Can not find it, do I have to do something to enable this function? Thanks!

### Describe the solution you'd like

Provide a start charging entity as button.

### Describe alternatives you've considered

--

### Additional context

<img width="860" alt="Bildschirmfoto 2024-07-17 um 10 16 24" src="https://github.com/user-attachments/assets/dfdd982b-d840-4139-9a28-bc66ed43aeb2">

**Comment by remuslazar** [comment]
@jchristianj: currently not implemented. Subject to change in future..

**Comment by remuslazar** [comment]
@jchristianj I have implemented the start charging button logic, nur currently released. Could you please test the testing branch if it works for you? (https://github.com/remuslazar/homeassistant-carwings/archive/refs/heads/testing.zip)

**Comment by jchristianj** [comment]
Thanks a lot for your efforts, especially the latest fix for the climate control switch. It is working great now! 
I am sorry, I do not know how to test the above branch... I installed your integration by adding the GitHub link as HACS repo, then downloaded it and added the integration. I am not sure how to handle a zip file?

**Comment by remuslazar** [comment]
@jchristianj the current release already contains this change. You could just update via HACS easily.
