### ISSUE TITLE
Implement a service call to fetch new data

### ISSUE THREAD

**Issue by RalfPfitzner** [remuslazar/homeassistant-carwings#9]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I would like to call the "update_nissan" service from Node Red to automatically set my charging station to the required energy.
Right now there is "only" the button to fetch new data.

### Describe the solution you'd like

Implement a service to be called (like in the other integration from filecole).

### Describe alternatives you've considered

No idea.

### Additional context

-

**Comment by remuslazar** [comment]
@RalfPfitzner you could also "press the button" from node red (I think) but adding the service for this seems to be a good idea, though.

**Comment by remuslazar** [comment]
@RalfPfitzner I have implemented the service call, currently there is an open PR. Could you test if everything works? You can checkout the "testing" branch for that purpose: https://github.com/remuslazar/homeassistant-carwings/archive/refs/heads/testing.zip

**Comment by RalfPfitzner** [comment]
Hi Remus,

unfortunately my Nissan in the repair shop right now (since 5 weeks!) and
not responding to status calls.

I will test in three weeks from now earliest, that's what Nissan promised.

Thanks
Ralf

Am Mi., 28. Aug. 2024 um 15:49 Uhr schrieb Remus Lazar <
***@***.***>:
